Repository jupyterhub/the-littlest-jupyterhub, pull requests merged in 2022-09, with the labels that each got.

#820 Update precommit
  .pre-commit-config.yaml
  tljh/installer.py
Labels: maintenance

#819 bootstrap script accepts a version
  bootstrap/bootstrap.py
  tests/test_bootstrap_functions.py
Labels: enhancement, priority

#817 ci: run int. and unit tests on 22.04 LTS + py3.10
  .github/workflows/integration-test.yaml
  .github/workflows/unit-test.yaml
Labels: ci

#826 docs: reference nbgitpullers docs to fix outdated tljh docs
  docs/howto/content/nbgitpuller.rst
  docs/images/nbgitpuller/binder-progress.png
  docs/images/nbgitpuller/blank-application.png
  docs/images/nbgitpuller/filepath-application.png
  docs/images/nbgitpuller/git-url-application.png
  docs/images/nbgitpuller/hub-url-application.png
Labels: documentation
