Repository jupyterhub/the-littlest-jupyterhub, pull requests merged in 2023-08, with the labels that each got.

#928 Update Notebook, JupyterLab, Jupyter Resource Usage
  integration-tests/test_extensions.py
  tljh/requirements-user-env-extras.txt
Labels: maintenance

#775 Launch into `/lab` by default by changing TLJH config's default value
  docs/conf.py
  docs/howto/user-env/notebook-interfaces.md
  docs/reference/changelog.md
  tests/test_configurer.py
  tljh/configurer.py
Labels: maintenance, breaking

#932 docs: add docs about environments and upgrades
  docs/conf.py
  docs/howto/admin/upgrade-tljh.md
  docs/howto/index.md
  docs/howto/user-env/notebook-interfaces.md
  docs/reference/changelog.md
  docs/topic/index.md
  docs/topic/installer-upgrade-actions.md
  docs/topic/three-environments.md
  docs/troubleshooting/index.md
  tljh/requirements-hub-env.txt
Labels: documentation

#933 Update changelog for 1.0.0 release
  docs/reference/changelog.md
  tljh/requirements-hub-env.txt
Labels: documentation
