Repository jupyterhub/the-littlest-jupyterhub, pull requests merged in 2023-06, with the labels that each got.

#914 Fix recently introduced failure to upper bound systemdspawner
  tljh/requirements-hub-env.txt
Labels: bug

#912 Stop bundling jupyterhub-configurator which has been disabled by default
  docs/topic/index.md
  docs/topic/jupyterhub-configurator.md
  tljh/configurer.py
  tljh/jupyterhub_configurator_config.py
  tljh/requirements-hub-env.txt
  tljh/user_creating_spawner.py
Labels: maintenance, breaking

#915 Update systemdspawner from version 0.17.* to >=1.0.1,<2
  tljh/requirements-hub-env.txt
  tljh/user_creating_spawner.py
Labels: maintenance, breaking

#916 maint: refactor tests, fix upgrade tests (now correctly failing)
  .github/integration-test.py
  .github/workflows/integration-test.yaml
  .github/workflows/unit-test.yaml
  bootstrap/bootstrap.py
  dev-requirements.txt
  integration-tests/Dockerfile
  integration-tests/plugins/simplest/tljh_simplest.py
  integration-tests/requirements.txt
  integration-tests/test_admin_installer.py
  integration-tests/test_bootstrap.py
  integration-tests/test_hub.py
  integration-tests/test_simplest_plugin.py
  pyproject.toml
  tests/test_bootstrap_functions.py
  tljh/installer.py
Labels: maintenance

#906 Google Cloud troubleshooting and configuration updates
  docs/howto/index.md
  docs/howto/providers/google.md
  docs/images/providers/google/boot-disk-edit-button.png
  docs/images/providers/google/boot-disk-resize-properties.png
  docs/images/providers/google/boot-disk-resize.png
  docs/images/providers/google/serial-port-console.png
  docs/troubleshooting/providers/google.md
Labels: help wanted, documentation

#919 test refactor: put bootstrap tests in an isolated job, save ~3 min in each of the integration test jobs
  .github/workflows/integration-test.yaml
Labels: maintenance

#920 --force-reinstall old conda to ensure it's working before we try to install conda packages
  tljh/conda.py
  tljh/installer.py
Labels: maintenance

#921 test refactor: add comment about python/conda/mamba
  tests/test_installer.py
Labels: maintenance
