Repository jupyterhub/the-littlest-jupyterhub, pull requests merged in 2023-05, with the labels that each got.

#883 Docs: Update DigitalOcean install instructions with new screenshot for "user data"
  docs/images/providers/digitalocean/additional-options.png
  docs/install/digitalocean.md
Labels: documentation

#880 update: jupyterhub 4
  integration-tests/test_hub.py
  tljh/installer.py
  tljh/requirements-base.txt
Labels: maintenance, breaking

#881 added `remove_named_servers` setting for jupyterhub-idle-culler
  docs/topic/idle-culler.md
  tests/test_configurer.py
  tljh/configurer.py
Labels: enhancement

#887 docs(awscognito): add custom claims example
  docs/howto/auth/awscognito.md
Labels: documentation

#891 pre-commit.ci configured to update pre-commit hooks on a monthly basis
  .pre-commit-config.yaml
Labels: maintenance

#893 pre-commit: add isort and autoflake
  .github/integration-test.py
  .pre-commit-config.yaml
  bootstrap/bootstrap.py
  docs/conf.py
  integration-tests/test_admin_installer.py
  integration-tests/test_bootstrap.py
  integration-tests/test_hub.py
  integration-tests/test_install.py
  integration-tests/test_proxy.py
  integration-tests/test_simplest_plugin.py
  pyproject.toml
  setup.py
  tests/conftest.py
  tests/test_bootstrap_functions.py
  tests/test_conda.py
  tests/test_config.py
  tests/test_configurer.py
  tests/test_installer.py
  tests/test_migrator.py
  tests/test_traefik.py
  tests/test_user.py
  tests/test_utils.py
  tljh/apt.py
  tljh/conda.py
  tljh/config.py
  tljh/hooks.py
  tljh/installer.py
  tljh/jupyterhub_config.py
  tljh/log.py
  tljh/migrator.py
  tljh/systemd.py
  tljh/traefik.py
  tljh/user_creating_spawner.py
  tljh/yaml.py
Labels: maintenance

#892 Upgrade pip in hub env from 21.3 to to 23.1 when bootstrap script runs
  .github/workflows/unit-test.yaml
  bootstrap/bootstrap.py
Labels: maintenance

#896 docs: disable navigation with arrow keys
  docs/conf.py
Labels: documentation

#861 Traefik v2, TraefikProxy v1
  integration-tests/conftest.py
  integration-tests/test_bootstrap.py
  integration-tests/test_proxy.py
  setup.py
  tests/test_configurer.py
  tests/test_traefik.py
  tljh/config.py
  tljh/configurer.py
  tljh/jupyterhub_config.py
  tljh/traefik-dynamic.toml.tpl
  tljh/traefik.py
  tljh/traefik.toml.tpl
Labels: enhancement, breaking

#898 Update Google auth docs
  docs/howto/auth/google.md
  docs/topic/tljh-config.md
Labels: documentation

#902 Add user env doc files
  docs/conf.py
  docs/howto/admin/admin-users.md
  docs/howto/admin/resource-estimation.md
  docs/howto/index.md
  docs/howto/user-env/notebook-interfaces.md
  docs/howto/user-env/server-resources.md
  docs/howto/user-env/user-environment.md
  docs/install/add-packages.md
  docs/install/add-users.md
  docs/install/amazon.md
  docs/install/azure.md
  docs/install/custom-server.md
  docs/install/digitalocean.md
  docs/install/google.md
  docs/install/jetstream.md
  docs/install/ovh.md
Labels: documentation

#900 Update nativeauthenticator, tmpauthenticator, and jupyterhub-configurator
  tljh/requirements-hub-env.txt
Labels: maintenance, breaking

#905 Add a Traefik configuration to listen on a specific address (#903)
  docs/topic/tljh-config.md
  tests/test_traefik.py
  tljh/config.py
  tljh/configurer.py
  tljh/traefik.toml.tpl
Labels: new
