Repository jupyterhub/the-littlest-jupyterhub, pull requests merged in 2023-04, with the labels that each got.

#842 update: jupyterhub 3, oauthenticator 15, systemdspawner 0.17 (user env: ipywidgets 8)
  integration-tests/test_hub.py
  tljh/installer.py
  tljh/requirements-base.txt
Labels: maintenance, breaking

#862 avoid registering duplicate log handlers
  tljh/log.py
Labels: maintenance

#870 docs: fix remaining issues following rst to myst transition
  docs/contributing/dev-setup.md
  docs/howto/admin/https.md
  docs/howto/auth/awscognito.md
  docs/howto/auth/github.md
  docs/howto/providers/azure.md
  docs/topic/tljh-config.md
Labels: documentation

#871 dependabot: monthly updates of github actions
  .github/dependabot.yaml
Labels: maintenance

#869 breaking, maint: remove deprecated nteract-on-jupyter
  docs/contributing/docs.md
  docs/contributing/packages.md
  docs/topic/tljh-config.md
  integration-tests/test_extensions.py
  tests/test_configurer.py
  tljh/configurer.py
  tljh/requirements-base.txt
Labels: maintenance, breaking

#876 maint: add upgrade test from main branch, latest release, and 0.2.0
  .circleci/config.yml
  .github/integration-test.py
  .github/workflows/integration-test.yaml
  .github/workflows/unit-test.yaml
  README.md
  bootstrap/bootstrap.py
  dev-requirements.txt
Labels: maintenance

#858 Update base user environment to mambaforge 23.1.0-1 (Python 3.10)
  .github/workflows/integration-test.yaml
  .github/workflows/unit-test.yaml
  dev-requirements.txt
  integration-tests/Dockerfile
  tests/test_conda.py
  tests/test_installer.py
  tljh/conda.py
  tljh/installer.py
  tljh/utils.py
Labels: maintenance, breaking

#878 docs: fix readme badge for tests
  README.md
Labels: documentation

#879 Typo : username -> admin-user-name
  docs/install/azure.md
Labels: documentation
