Repository jupyterhub/the-littlest-jupyterhub, pull requests merged in 2024-09, with the labels that each got.

#976 Add TLJH config lockfile
  dev-requirements.txt
  integration-tests/requirements.txt
  tljh/config.py
  tljh/requirements-hub-env.txt
Labels: maintenance

#990 Update base user environment to miniforge 24.7.1-0 (Python 3.12)
  docs/topic/installer-actions.md
  tests/test_conda.py
  tests/test_installer.py
  tljh/installer.py
Labels: maintenance

#942 Add the ability to define conda channels in plugins via `tljh_extra_user_conda_channels`
  integration-tests/plugins/simplest/tljh_simplest.py
  integration-tests/test_simplest_plugin.py
  tests/test_conda.py
  tljh/conda.py
  tljh/hooks.py
  tljh/installer.py
Labels: new

#992 update oauthenticator to 17
  docs/howto/auth/awscognito.md
  tljh/requirements-hub-env.txt
Labels: maintenance

#993 ci: run unit tests in ubuntu-24.04 github actions environment as well
  .github/workflows/unit-test.yaml
  tests/test_config.py
Labels: ci

#994 consolidate lock file handling
  dev-requirements.txt
  integration-tests/requirements.txt
  setup.py
  tljh/config.py
  tljh/requirements-hub-env.txt
Labels: maintenance

#997 ci: cache pip only when no container is used
  .github/workflows/integration-test.yaml
  .github/workflows/unit-test.yaml
Labels: ci

#998 Drop ubuntu 20.04, require py39, traefik-proxy v2, and ldapauthenticator v2
  .github/integration-test.py
  .github/workflows/integration-test.yaml
  .pre-commit-config.yaml
  bootstrap/bootstrap.py
  integration-tests/test_bootstrap.py
  integration-tests/test_extensions.py
  pyproject.toml
  setup.py
  tests/test_config.py
  tljh/requirements-hub-env.txt
Labels: maintenance, breaking

#999 Update to install miniforge 24.7.1-2 from 24.7.1-0
  tljh/installer.py
Labels: maintenance

#1002 Bump the requirements-user-env-extras.txt lower version bounds
  tljh/requirements-user-env-extras.txt
Labels: maintenance

#1001 Update traefik from 2.10.1 to 3.1.4
  tljh/installer.py
  tljh/traefik.py
Labels: maintenance

#1003 Test upgrade from 1.*
  .github/workflows/integration-test.yaml
Labels: ci

#1000 Add changelog for 2.0.0b1
  docs/reference/changelog.md
Labels: documentation
